### ISSUE TITLE
Invalid address 0x48c is pointing to reserved memory.

### ISSUE THREAD

**Issue by KeithGDR** [Ilusion9/entityIO-sm#1]
`L 09/16/2023 - 22:22:44: [SM] Exception reported: Invalid address 0x48c is pointing to reserved memory.
L 09/16/2023 - 22:22:44: [SM] Blaming: entityIO.smx
L 09/16/2023 - 22:22:44: [SM] Call stack trace:
L 09/16/2023 - 22:22:44: [SM]   [0] LoadFromAddress
L 09/16/2023 - 22:22:44: [SM]   [1] Line 590, entityIO.sp::GetStringFromAddress
L 09/16/2023 - 22:22:44: [SM]   [2] Line 1135, entityIO.sp::Native_GetEntityOutputName
L 09/16/2023 - 22:22:44: [SM]   [4] EntityIO_GetEntityOutputName
L 09/16/2023 - 22:22:44: [SM]   [5] Line 183, D:\pawn\scripting\weapons.sp::DisplayEntityOutputs
L 09/16/2023 - 22:22:44: [SM]   [6] Line 85, D:\pawn\scripting\weapons.sp::Event_OnRoundStart`

Any useful information on this? I'm not sure personally.

**Comment by Ilusion9** [comment]
what game?

**Comment by KeithGDR** [comment]
Counter-Strike: Source

**Comment by Ilusion9** [comment]
on windows everything works fine, i cannot test on linux
try to add this in gamedata

```
	"cstrike"
	{
		"Offsets"
		{
			"typedescription_t::externalName"
			{
				"windows"		"20"
				"linux"			"24"
				"mac"			"24"
			}
			
			"sizeof::typedescription_t"
			{
				"windows"		"52"
				"linux"			"56"
				"mac"			"56"
			}
		}
	}
```

**Comment by KeithGDR** [comment]
So far that seems to be working, thank you.
